server:
  port: 8091
spring:
  application:
    name: work_order
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://postgres-local:5432/drools?currentSchema=wo"
    username: "drools"
    password: "drools"
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
chaos:
  monkey:
    enabled: false

