server:
  port: 8091
spring:
  application:
    name: work_order
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/drools?currentSchema=wo"
    username: "drools"
    password: "drools"
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    enabled: true
chaos:
  monkey:
    enabled: false

