spring:
  datasource:
    url: "jdbc:postgresql://host.docker.internal:5432/drools?currentSchema=wo"
    username: "drools"
    password: "drools"
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: wo-group-2
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0





