server:
  port: 8091
spring:
  application:
    name: work_order
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/work_order"
    username: "drools"
    password: "drools"
  flyway:
    enabled: false
    baselineOnMigrate: false
    validateOnMigrate: false
    locations: classpath:db/migration
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    enabled: false
chaos:
  monkey:
    enabled: false

